name: turnos_amerisa
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  table_calendar: ^3.1.1
  awesome_dialog: ^3.2.1
  flutter_rating_bar: ^4.0.1
  awesome_notifications_core: ^0.9.0
  awesome_notifications: ^0.9.3+1
  http: ^1.2.1
  fluttertoast: ^8.2.6
  mysql1: ^0.20.0
  shared_preferences: ^2.2.3
  flutter_bloc: ^8.1.5
  get: ^4.6.6
  firebase_core: ^3.1.1
  firebase_messaging: ^15.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true
