// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDG4mMWgiS1_-hrCj67DrVpmR2w9lbheV8',
    appId: '1:510465002957:web:a0015fa767f9e754dcc884',
    messagingSenderId: '510465002957',
    projectId: 'turnosamerisa',
    authDomain: 'turnosamerisa.firebaseapp.com',
    storageBucket: 'turnosamerisa.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPsBsd9Io_6vi9poZ2yLLQ8iluahCr0hk',
    appId: '1:510465002957:android:268f3b3e5eb1272bdcc884',
    messagingSenderId: '510465002957',
    projectId: 'turnosamerisa',
    storageBucket: 'turnosamerisa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB36EYQJB9qUigD6SYWdFuVHzhGZpqKVSo',
    appId: '1:510465002957:ios:04dade45abb74a51dcc884',
    messagingSenderId: '510465002957',
    projectId: 'turnosamerisa',
    storageBucket: 'turnosamerisa.appspot.com',
    iosBundleId: 'com.example.turnosAmerisa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB36EYQJB9qUigD6SYWdFuVHzhGZpqKVSo',
    appId: '1:510465002957:ios:04dade45abb74a51dcc884',
    messagingSenderId: '510465002957',
    projectId: 'turnosamerisa',
    storageBucket: 'turnosamerisa.appspot.com',
    iosBundleId: 'com.example.turnosAmerisa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDG4mMWgiS1_-hrCj67DrVpmR2w9lbheV8',
    appId: '1:510465002957:web:66feb0d1ab5d0676dcc884',
    messagingSenderId: '510465002957',
    projectId: 'turnosamerisa',
    authDomain: 'turnosamerisa.firebaseapp.com',
    storageBucket: 'turnosamerisa.appspot.com',
  );
}
